# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['spyder\\app\\start.py'],
             pathex=['C:\\Users\\Daniel\\Documents\\Spyder\\spyder'],
             binaries=[],
             datas=[('README.md', '.'),
                    ('MANIFEST.in', '.'),
                    ('LICENSE.txt', '.'),
                    ('AUTHORS.txt', '.'),
                    ('NOTICE.txt', '.'),
                    ('bootstrap.py', '.'),
                    ('scripts/*', '.'),
                    ('img_src/*.ico', '.'),
                    ('img_src/spyder.png', '.'),
                    ('img_src/spyder3.png', '.'),
                    ('img_src/oxygen_icon_set/*', '.'),
                    ('spyder/fonts/*', 'spyder/fonts'),
                    ('spyder/locale/*', 'spyder/locale'),
                    ('spyder/plugins/help/utils*',
                     'spyder/plugins/help/utils'),
                    ('spyder/plugins/completion/kite/bloomfilter/*',
                     'spyder/plugins/completion/kite/bloomfilter'),
                    ('spyder/plugins/ipythonconsole/assets/templates*',
                    'spyder/plugins/ipythonconsole/assets/templates'),],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='spyder',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='spyder')
